name: "Check Links"

on:
    push:
      branches:
        - main
    pull_request:
    workflow_dispatch:

jobs:
  check-links:
    name: Detect Broken Links
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1

